import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {initializeTestEnvironment,assertFails,assertSucceeds} from '@firebase/rules-unit-testing';
import {doc,getDoc,setDoc} from 'firebase/firestore';
import {initializeApp,deleteApp} from '../../functions/node_modules/firebase-admin/lib/esm/app/index.js';
import {getFirestore} from '../../functions/node_modules/firebase-admin/lib/esm/firestore/index.js';
import {uiApi,dailyBackup,manageUsers} from '../../functions/ui-api.mjs';
import {commitMutations} from '../../functions/mutations.mjs';

test('React API shares legacy inventory atomically and enforces conflicts, undo, backup and access',async()=>{
  const projectId='demo-react-warehouse';process.env.FIRESTORE_EMULATOR_HOST='127.0.0.1:8087';
  const env=await initializeTestEnvironment({projectId,firestore:{host:'127.0.0.1',port:8087,rules:fs.readFileSync('firestore.rules','utf8')}});
  const app=initializeApp({projectId},'react-api-tests'),db=getFirestore(app);
  const auth=uid=>({uid,token:{email:uid+'@example.test',auth_time:Math.floor(Date.now()/1000)}});
  const api=(path,method='GET',body={},uid='admin')=>uiApi(db,auth(uid),{path,method,body});
  try{
    await env.clearFirestore();await db.doc('roles/admin').set({tier:2});await db.doc('roles/staff').set({tier:1});
    await assert.rejects(uiApi(db,null,{path:'/api/locations'}),{status:401});
    await assert.rejects(api('/api/locations','GET',{},'stranger'),{status:403});
    await assert.rejects(api('/api/products','POST',{code:'BOLT',name:'볼트'},'staff'),{status:403});
    await api('/api/products','POST',{code:'BOLT',name:'볼트'});
    const item={code:'BOLT',name:'볼트',qty:12,threshold:3,lot:'L',expiry:''};
    const change={cellKey:'1-1',baseItems:[],items:[item],type:'receipt',reason:'테스트 입고'};
    await api('/api/locations/S01/cell','PUT',change,'staff');
    const shelf=(await db.doc('shelves/shelf-5').get()).data();
    assert.equal(shelf.cells[0].list[0].qty,12);assert.equal(shelf.cells[0].list[0].code,undefined);
    await assert.rejects(api('/api/locations/S01/cell','PUT',change),{code:'CELL_CONFLICT'});
    await api('/api/locations/S02/cell','PUT',change);
    const adjustment={...change,baseItems:[item],items:[{...item,threshold:5}],type:'adjustment',reason:'기준 변경'};
    await assert.rejects(api('/api/locations/S01/cell','PUT',adjustment),{code:'THRESHOLD_CONFLICT'});
    await api('/api/locations/S01/cell','PUT',{...adjustment,syncThresholds:true});
    assert.equal((await db.doc('shelves/shelf-4').get()).data().cells[0].list[0].threshold,5);
    const entry=(await api('/api/ledger')).entries.find(e=>e.type==='adjustment');
    await api('/api/ledger/'+entry.id+'/undo','POST',{reason:'테스트 취소'});
    assert.equal((await db.doc('shelves/shelf-4').get()).data().cells[0].list[0].threshold,3);
    await assert.rejects(api('/api/ledger/'+entry.id+'/undo','POST',{reason:'중복 취소'}),{code:'UNDO_UNAVAILABLE'});
    const latest=(await api('/api/locations')).locations.find(l=>l.id==='S01');
    await assert.rejects(api('/api/locations/S01/structure','PUT',{version:latest.version,rows:3,cols:9}),{code:'INVALID_STRUCTURE'});
    await api('/api/locations/S01/structure','PUT',{version:latest.version,rows:2,cols:12});
    const saved=await api('/api/backups','POST');
    const revision=(await api('/api/revision')).revision;
    await api('/api/locations/S01/cell','PUT',{...change,baseItems:[item],items:[{...item,qty:11}],type:'issue',reason:'출고'});
    const newlyCreated=await api('/api/locations/S03/cell','PUT',change);
    const newVersion=newlyCreated.locations.find(l=>l.id==='S03').version;
    await assert.rejects(api('/api/backups/'+saved.id+'/restore','POST',{revision,reason:'복원'}),{code:'VERSION_CONFLICT'});
    const restored=await api('/api/backups/'+saved.id+'/restore','POST',{revision:(await api('/api/revision')).revision,reason:'복원'});
    assert.ok(restored.locations.find(l=>l.id==='S03').version>newVersion);
    assert.deepEqual(restored.locations.find(l=>l.id==='S03').cells['1-1'],[]);
    assert.equal((await db.doc('shelves/shelf-5').get()).data().cells[0].list[0].qty,12);
    await dailyBackup(db);await dailyBackup(db);
    assert.equal((await api('/api/backups')).backups.filter(b=>b.id.startsWith('daily-')).length,1);
    assert.ok((await api('/api/backups/'+saved.id+'/download')).documents['shelves/shelf-5']);
    // Original writer still sees the shared revision and can save without a schema migration.
    const shared=(await db.doc('shelves/shelf-5').get()).data();
    const {_revision,...data}=shared;
    await commitMutations(db,auth('staff'),[{path:'shelves/shelf-5',expectedRevision:_revision,data}]);
    const receipt=(await api('/api/ledger')).entries.find(e=>e.type==='receipt'&&e.locationId==='S01');
    await assert.rejects(api('/api/ledger/'+receipt.id+'/undo','POST',{reason:'충돌 확인'}),{code:'UNDO_CONFLICT'});
    const client=env.authenticatedContext('staff',auth('staff').token).firestore();
    await assertSucceeds(getDoc(doc(client,'uiProducts/BOLT')));
    await assertFails(setDoc(doc(client,'uiProducts/BOLT'),{code:'BOLT',name:'침입'}));
    await assertFails(getDoc(doc(client,'uiBackups/'+saved.id)));
    await db.doc('roles/staff').update({sessionValidAfter:Math.floor(Date.now()/1000)+10});
    await assertFails(getDoc(doc(client,'uiProducts/BOLT')));
    await assert.rejects(api('/api/locations','GET',{},'staff'),{status:401});
    await assert.rejects(manageUsers(db,{},auth('staff'),{path:'/api/users'}),{status:403});
    await db.doc('pallets/pallet-4').set({items:[{name:'볼트',qty:7,threshold:3,lot:'L',expiry:''}],_revision:1});
    const pallet=(await api('/api/locations')).locations.find(l=>l.id==='P03');
    await api('/api/locations/P03/cell','PUT',{cellKey:'1-1',baseItems:pallet.cells['1-1'],items:[],type:'issue',reason:'묶음 비우기'});
    assert.deepEqual((await db.doc('pallets/pallet-4').get()).data().items,[]);
    assert.deepEqual((await db.doc('pallets/pgroup-pallet-5').get()).data().items,[]);
    const fakeAuth={createUser:async()=>({uid:'new-staff'}),updateUser:async()=>({}),revokeRefreshTokens:async()=>{},deleteUser:async()=>{},getUsers:async ids=>({users:ids.map(({uid})=>({uid,email:uid+'@example.test'}))})};
    const accounts=request=>manageUsers(db,fakeAuth,auth('admin'),request);
    await accounts({path:'/api/users',method:'POST',body:{email:'new@example.test',name:'새 담당자',role:1,password:'TestPassword123'}});
    assert.equal((await db.doc('roles/new-staff').get()).data().tier,1);
    await accounts({path:'/api/users/new-staff',method:'PUT',body:{name:'중지한 담당자',role:0}});
    assert.equal((await db.doc('roles/new-staff').get()).data().tier,0);
    await assert.rejects(accounts({path:'/api/users/admin',method:'PUT',body:{name:'관리자',role:0}}),{code:'SELF_DEMOTION'});
    assert.ok((await accounts({path:'/api/users'})).users.some(u=>u.id==='admin'));
  }finally{await env.cleanup();await deleteApp(app);}
});
